#!/usr/bin/env python3
# TODO
from helpers import get_user_timeline
import sys
from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    analyzer = Analyzer()
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile @user")
    timeline = get_user_timeline(sys.argv[1][1:],count=200)
    for i in timeline:
        score = analyzer.analyze(i)
        if score > 0.0:
            print(colored("%s %s", "green")% (score, i))
        elif score < 0.0:
            print(colored("%s %s", "red")% (score, i))
        else:
            print(colored("%s %s", "yellow")% (score, i))
if __name__ == "__main__":
     main()
